In [22]:
import cv2
import numpy as np

In [3]:
kernel = np.ones((5,5),np.uint8)
print(kernel)

path = 'C:/testcam/github/fourier_converter/dataset/3.jpg'

img = cv2.imread(path)
imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2.imshow("face",img)
cv2.imshow("GrayScale",imgGray)
cv2.waitKey(0)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


-1

In [41]:
path1 = 'C:/testcam/datatest/fakerepic/170906.jpg'
path2 = 'C:/testcam/datatest/fakerepic/170980.jpg'

img1 = cv2.imread(path1)
#img2 = cv2.imread(path2,0)

print(img1.shape)
#print(img2.shape)

imgGray = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
print(imgGray.shape)

img1 = cv2.resize(img1, (0,0), None, 0.5, 0.5)
imgGray = cv2.resize(imgGray, (0,0), None, 0.5, 0.5)

hor = np.hstack((img1, imgGray))

cv2.imshow('Hori',hor)

cv2.waitKey(0)

(1477, 1108, 3)
(1477, 1108)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [46]:
def stackImage(scale,imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0],list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range (0, rows):
            for y in range (0, cols):
                if imgArray[x][y].shape[:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize((imgArray[x][y],(imgArray[0][0].shape[1], (imgArray[0][0].shape[0]), None, scale, scale),
                    len(imgArray[x][y].shape) == 2: imgArray[x][y] = cv2.cvtColor(imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height,width,3),np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0 ,rows):
            if imgArray[x].shape == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0,0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize((imgArray[x], (imgArray[0].shape[1], (imgArray[0].shape[0]), None, scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor = np.hstack(imgArray)
        ver = hor
    return ver

SyntaxError: invalid syntax (Temp/ipykernel_11772/1555782600.py, line 14)